[package]
name = "common_subscriber"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.com>"]
edition = "2021"

[lib]
path = "src/common_subscriber.rs"

[dependencies.subscription-fee]
path = "../../subscription-fee"

[dependencies.dharitri-sc]
version = "=0.13.4"
